# Generated by Django 4.1.2 on 2023-08-19 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0002_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
